import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="pt-16">
          <div className="fixed inset-x-0 top-0 z-50 bg-white border-b border-black/10">
            <div className="h-16 flex items-center px-3">
              <Link href="/" aria-label="Home" className="inline-flex items-center">
                <Image
                  src="/rakuten-logo.png"
                  alt="App icon"
                  width={120}
                  height={40}
                  priority
                />
              </Link>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}


